# Generated by Django 5.1.7 on 2025-05-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=140, unique=True)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('escolaridade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
