# Generated by Django 5.1.7 on 2025-05-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vagas',
            new_name='Vaga',
        ),
    ]
