# Generated by Django 5.2.1 on 2025-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0002_rename_vagas_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('FUN', 'Fundamental'), ('MED', 'Médio'), ('SUP', 'Superior'), ('POS', 'Pós-graduação'), ('MES', 'Mestrado'), ('DOC', 'Doutorado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não-binário'), ('O', 'Outro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='area',
            field=models.CharField(choices=[('I', 'Informática'), ('T', 'Tecnologia'), ('E', 'Enfermagem')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('E', 'Estágio'), ('C', 'CLT'), ('CP', 'Cooperativa'), ('P', 'PJ')], max_length=2),
        ),
    ]
