# Generated by Django 5.1.6 on 2025-05-14 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0003_alter_candidato_escolaridade_alter_candidato_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='empregos.vaga'),
        ),
    ]
